version: "3"

services:
  ticketing-api:
    container_name: ticketing-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - PORT=${PORT:-9091}
    image: catcatio/ticketing-api
    working_dir: /usr/app
    ports:
      - "${PORT:-9091}:${PORT:-9091}"
    volumes:
      - .:/usr/app
    command: npm run init
